---
# tasks file for ansible-role-logging/

- name: "Include OS-specific variables"
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yaml"

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when:
    - ansible_facts.packages is not defined

- name: "Install required packages, if not already installed"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
  when:
    - item|string not in ansible_facts.packages

- name: "Include tasks from rsyslog playbook"
  ansible.builtin.include_tasks: rsyslog.yaml

- name: "Include tasks from LogRotate playbook"
  ansible.builtin.include_tasks: LogRotate.yaml

- name: "Configure journald settings in config file"
  ansible.builtin.replace:
    path: /etc/systemd/journald.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
    backup: yes
  with_items:
    - regexp: '#Compress=yes'
      replace: 'Compress=yes'
    - regexp: '#ForwardToSyslog=yes'
      replace: 'ForwardToSyslog=yes'
    - regexp: '#Storage=auto'
      replace: 'Storage=persistent'
